### ISSUE TITLE
Error: Cannot find module 'express'

### ISSUE THREAD

**Issue by foxpcteam** [paypal/AATT#19]
Hi,
when i run` $ DEBUG=AATT* http_port=3000 node app.js` i get this error

```
Error: Cannot find module 'express'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/user/AATT/app.js:2:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

**Comment by mpnkhan** [comment]
npm install should solve this.
