### ISSUE TITLE
Getting error unexpected token at line 165 - app.js

### ISSUE THREAD

**Issue by emfluenceindia** [paypal/AATT#40]
$ DEBUG=AATT* http_port=80 node app.js giving the following error:

```
/var/www/html/tourplanner/AATT/app.js:165
				fs.unlink(tempFilename, (err) => {
				                               ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3
```

OS: Ubuntu 14.04

**Comment by mpnkhan** [comment]
Looks like you have old version of nodejs.

**Comment by emfluenceindia** [comment]
@mpnkhan Thank you for your reply. I will upgrade to the latest and try again. Would share my findings.
